// File generated by FlutterFire CLI / Antigravity
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1kfgbLGQiLPE2BiOxNo6X0P5fv28TW3s',
    appId: '1:441957107322:web:27531efb97a2583bc25dc3',
    messagingSenderId: '441957107322',
    projectId: 'worker-management-app-4bd79',
    authDomain: 'worker-management-app-4bd79.firebaseapp.com',
    storageBucket: 'worker-management-app-4bd79.firebasestorage.app',
    measurementId: 'G-0TQSXRC0JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1kfgbLGQiLPE2BiOxNo6X0P5fv28TW3s',
    appId: '1:441957107322:android:7c36bfe5683eb588c25dc3',
    messagingSenderId: '441957107322',
    projectId: 'worker-management-app-4bd79',
    storageBucket: 'worker-management-app-4bd79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1kfgbLGQiLPE2BiOxNo6X0P5fv28TW3s',
    appId: '1:441957107322:ios:1817b8f4608f769cc25dc3',
    messagingSenderId: '441957107322',
    projectId: 'worker-management-app-4bd79',
    storageBucket: 'worker-management-app-4bd79.firebasestorage.app',
    iosBundleId: 'com.workerapp.workerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1kfgbLGQiLPE2BiOxNo6X0P5fv28TW3s',
    appId: '1:441957107322:ios:1817b8f4608f769cc25dc3',
    messagingSenderId: '441957107322',
    projectId: 'worker-management-app-4bd79',
    storageBucket: 'worker-management-app-4bd79.firebasestorage.app',
    iosBundleId: 'com.workerapp.workerApp',
  );
}
